<a href="https://colab.research.google.com/github/EnasIbrahimAli2005/Arabic-Sentiment-Analysis-Project/blob/main/Arabic_Sentiment_Analysis(Enas_Ibrahiem).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install imbalanced-learn

Requirement already satisfied: imbalanced-learn in /usr/local/lib/python3.10/dist-packages (0.12.3)
Requirement already satisfied: numpy>=1.17.3 in /usr/local/lib/python3.10/dist-packages (from imbalanced-learn) (1.26.4)
Requirement already satisfied: scipy>=1.5.0 in /usr/local/lib/python3.10/dist-packages (from imbalanced-learn) (1.13.1)
Requirement already satisfied: scikit-learn>=1.0.2 in /usr/local/lib/python3.10/dist-packages (from imbalanced-learn) (1.3.2)
Requirement already satisfied: joblib>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from imbalanced-learn) (1.4.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from imbalanced-learn) (3.5.0)

In [ ]:
!pip install scikit-learn

Requirement already satisfied: scikit-learn in /usr/local/lib/python3.10/dist-packages (1.3.2)
Requirement already satisfied: numpy<2.0,>=1.17.3 in /usr/local/lib/python3.10/dist-packages (from scikit-learn) (1.26.4)
Requirement already satisfied: scipy>=1.5.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn) (1.13.1)
Requirement already satisfied: joblib>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from scikit-learn) (1.4.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn) (3.5.0)

In [ ]:
!pip install pyarabic

Collecting pyarabic
  Downloading PyArabic-0.6.15-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: six>=1.14.0 in /usr/local/lib/python3.10/dist-packages (from pyarabic) (1.16.0)
Downloading PyArabic-0.6.15-py3-none-any.whl (126 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 126.4/126.4 kB 2.4 MB/s eta 0:00:00
Installing collected packages: pyarabic
Successfully installed pyarabic-0.6.15

In [ ]:
from datasets import load_dataset
ds = load_dataset("josephnashat/ArabicSentimentAnalysis")

In [ ]:
import pandas as pd
import re
from pyarabic.araby import strip_tashkeel

In [ ]:
ds

DatasetDict({
    train: Dataset({
        features: ['text', 'polarity'],
        num_rows: 964
    })
})

In [ ]:
ds["train"][0]

{'text': 'المكان الذي يمكنك فيه مراجعة الذات والتفكر هو كوكروبيت، غانا....  \nثمة الكثير عند زيارة غانا. وعلى الرغم من الفقر الذي سوف تلاحظه على طريقك إلى بيغ ميلي باكيارد، وجدت أن الناس في غانا يملكون ثراء القلب حتى رغم العوز. بيغ ميلي باكيارد هو مكان يمكنني فيه مراجعة الذات والتفكر . التقيت أشخاصاً كانوا يعملون على مبادرات مختلفة. بيغ ميلي هو مكان يمكننا فيه تبادل الملاحظات والآراء. بيغ ميلي مليء بالسلام وهادئ للغاية . الطعام ممتاز جداً! الطهاة ممتازون! وبالإضافة إلى ذلك, لا بد من الإشارة إلى أن العمال الذين لا يكلون، ويحرصون على سعادة نزلائهم هم من يجعلون المكان مضيافاً. هناك خيبة أمل واحدة كبيرة!! رغم أن الفنون والأشغال اليدوية يمكن شراؤها في الموقع إلا أن الأسعار غالية!!! مؤخراً أزالت السلطات في كوكروبيت محلات التجار الواقعة خارج شاطئ بيغ ميلي. كانت منتجات التجار أرخص! لا يزال هناك محل تجاري "متجر مايسترو للفن الإفريقي في كوكروبيت" يعرض الفنون والأشغال اليدوية الفريدة والملابس واللوحات. اشتريت لوحات مذهلة لايمكنك أن تجدها في بيغ ميلي. عندما تزور بيغ ميلي من فضلك خذ لحظة للذهاب إلى الشاطئ وعلى يمينك ستجد "متجر مايسترو للفن الإفريقي" المذهل. لا تنخدع بأسعار التجار في بيغ ميلي باكيارد. استمتع بالموسيقى والناس! الرجاء أن تقضي وقتاً ممتعاً.',
 'polarity': 1}

In [ ]:
df = pd.DataFrame(ds['train'])

In [ ]:
df

,text,polarity
0,"المكان الذي يمكنك فيه مراجعة الذات والتفكر هو كوكروبيت، غانا.... \nثمة الكثير عند زيارة غانا. وعلى الرغم من الفقر الذي سوف تلاحظه على طريقك إلى بيغ ميلي باكيارد، وجدت أن الناس في غانا يملكون ثراء القلب حتى رغم العوز. بيغ ميلي باكيارد هو مكان يمكنني فيه مراجعة الذات والتفكر . التقيت أشخاصاً كانوا يعملون على مبادرات مختلفة. بيغ ميلي هو مكان يمكننا فيه تبادل الملاحظات والآراء. بيغ ميلي مليء بالسلام وهادئ للغاية . الطعام ممتاز جداً! الطهاة ممتازون! وبالإضافة إلى ذلك, لا بد من الإشارة إلى أن العمال الذين لا يكلون، ويحرصون على سعادة نزلائهم هم من يجعلون المكان مضيافاً. هناك خيبة أمل واحدة كبيرة!! رغم أن الفنون والأشغال اليدوية يمكن شراؤها في الموقع إلا أن الأسعار غالية!!! مؤخراً أزالت السلطات في كوكروبيت محلات التجار الواقعة خارج شاطئ بيغ ميلي. كانت منتجات التجار أرخص! لا يزال هناك محل تجاري ""متجر مايسترو للفن الإفريقي في كوكروبيت"" يعرض الفنون والأشغال اليدوية الفريدة والملابس واللوحات. اشتريت لوحات مذهلة لايمكنك أن تجدها في بيغ ميلي. عندما تزور بيغ ميلي من فضلك خذ لحظة للذهاب إلى الشاطئ وعلى يمينك ستجد ""متجر مايسترو للفن الإفريقي"" المذهل. لا تنخدع بأسعار التجار في بيغ ميلي باكيارد. استمتع بالموسيقى والناس! الرجاء أن تقضي وقتاً ممتعاً.",1
1,موقع رائع وحديقة رائعة ويستحق نجمةّ إضافية \nعلى الرغم من أن الغرف ليست فاخرة، فهي نظيفة جداً وتعمل بشكل مثالي. بالتأكيد هناك بعض التصرفات الفردية والجماعية، ولكن كان هناك تكييف هواء كبير وجيد ونوافذ مزدوجة جيدة مع شاشات. منطقة الحديقة تحتوى على 3 مطاعم بالإضافة إلى بار رياضي. تبلغ تكلفة الإنترنت اللاسلكي 1:50 دولار للساعة، ولا يوجد خصم على الفترات الأطول، لذلك اضطررت إلى إغلاق حاسوبي أكثر. إف و بي رخيص جداً. يبدو أن هناك العديد من الزوار الأجانب هناك. 85 دولار أمريكي لليلة بما في ذلك بوفيه إفطار بمستوى نجمة واحدة. إقامة أفضل بكثير مما اعتقدت، سنعود بالتأكيد. شملت الإقامات السابقة فندق الأفريقية ريجنت و الدخول بالمطار غرب فندق (خيارريجينت أفريكان وفندق إيربيورت ويست (خيار قوي لتلك المنطقة من المدينة). حركة المرور في أكرا مُصابة بالشلل، لذا قم بعقد اجتماعاتك في فندق بالوما - وهو معروف جيداً.,0
2,أسوأ فندق أقمت فيه على الإطلاق \nيستغرق تسجيل الوصول حوالي 30 دقيقة، باهظ الثمن، غرف قديمة جداً وقذرة، سجادة قذرة جداً... فى المجمل تجربة سيئة للغاية.\nمثل هذا الفندق سيكون في آسيا، نجمة واحدة، ويمكن أن أذهب في مايو.\n30 دولار أمريكي.\nالسعر في فندق نوفوتيل حوالي 250 دولار أمريكي\n,-1
3,بدون روح كأنه فندق ثلاثة نجوم \nبدون إدارة احترافية، فإن هذا الفندق يبدو كمركب ضائع في البحر.\nالغرف موزعة بطريقة عشوائية والإفطار هو نقانق باردة سخيفة ونفس السلطة القديمة في كل يوم.\nكان مكيف الهواء يثير الضوضاء في الغرفة ومن المستحيل إيقافه.\nولكن مركز صحي رائع\n,0
4,فندق جميل مع سوء الإدارة والخدمات. \nمن الخارج بدا مبشرًا، لكن خيبة الأمل بدأت في وقت الغداء، جودة الطعام سيئة سيئة سيئة، والحساء كان مزريًا جدًا، والفواكه جودتها سيئة (البكيخ كان متعفنًا، واو!). اشتكى زملائي من عدم وجود مناشف في غرفهم في حوالي الساعة 8 مساءً، والبعض لم تكن أسرّتهم مرتبة حتى الساعة 5 مساءً. تناولنا عشاء مكسيكيًا ومرة أخرى كانت قائمة الطعام مزرية. لن أقيم هنا أبدًا، على الأقل أتحدث عن نفسي!,-1
...,...,...
959,ما تتوقعه من فندق Premier \nإذا اقمت في فندق Premier الصغير في المملكة المتحدة، فأنت تعلم ما تتوقعه في هذا الفندق، فهو تقريبًا متسق مع نفس المستوى القياسي. كانت الغرف نظيفة وبها ديكورات جميلة وواسعة. لا توجد مرافق كثيرة لكن يوجد حمام سباحة صغير بالطابق الأخير وبار/مطعم ومحل Costa مفتوح 24 ساعة. الفندق قري من المطار لكن مسافة لا يمكن قطعها سيرًا. سيلزم ركوب أتوبيس يغادر كل 30 دقيقة. أقرب محطة مترو (الإمارات) على مسافة 15 دقيقة سيرًا. يدير الفندق أتوبيسات إلى العديد من الأماكن. اتسم طاقم العمل بالترحاب والانتباه وكان الفندق منعزلاً بشكل جيد عن ضوضاء المطار.\n,1
960,فندق 3 نجوم تنافسي جدًا \nكان فندق الأجازات الصغير Premier محبطًا إلى حد ما. أقمت في هذا الفندق لمدة ليلة واحدة أثناء رحلتي إلى تايلاند في يناير وعودتي في فبراير. اتسم طاقم العمل بالود الشديد وبدا الأمر كما يتم الترويج له في الإعلانات. كان يوجد عدد كاف من طاقم العمل عند تسجيل الدخول (كان يوجد 3 أو 4 مقابل 1 في الفندق المجاور) كانت الغرفة مريحة وفوق المتوسط بالنسبة لهذه الفئة (تتضمن سخان مياه للقهوة والشاي). كان النوم رائعًا من ناحية السرير وانعدام الضوضاء. كما كان سائق الأتوبيس ودودًا ويبدو سعيدًا بمساعدة الغير، وكانت ماعيد منضبطة بالساعة ونصف الساعة. الشيء السلبي هو الفطائرة التي يتم تقديمها في الفطور لكن يبدوأنه يوجد محل قهوة عند المدخل مفتوح 24 ساعة. نقطة أخيرة: الأسعار تنافسية مع الفنادق الأخرى القريبة من المطار (10 دقائق بالأتوبيس). رغم أن الفطورلم يكن متضمنًا (بعض الفنادق تقدم فطورًا مجانيًا). الاختيار لك!\n,1
961,يمكن أن أقيم فيه مجددًا! \nالفندق جديد و قد تم تشطيبه وفقا لمواصفات غاية في الجودة. طاقم العمل معظمهم من الشرق و هم غاية في اللطف و التعاون. الغرف مزودة بتقنية تكنولوجية عالية ذات نظام تحكم رقمي للإضاءة و الستائر إلخ..إضافة إلي مستلزمات فائقة الجودة لدورات المياه.كان السعر متميز جدا و لكنه اختلف كثيرا بناء علي من قام بالحجز.استخدم بعد المواقع الخاصة بالمقارنة لمعرفة أفضل الأسعار.يقع بالقرب من ميناء كروز و يتكلف التاكسي 40 درهم اماراتي ( 12 دولار امريكي).أما عن العيوب..النوم ليس مزعج علي متن الطائرة إلا أن سقف البار ليس موجود تقريبا لذلك قد تعلو الضوضاء في بعض الأحيان.و كذلك خدمة الواي فاي المجانية ليست فقط متقلبقة و لكن تتطلب تغيير كلمة السر بشكل يومي إضافة إلي كونها بطيئة جدا و لا تقبل تجديد الإيميل لذلك كان علي فعل ذلك بمركز دبي التجاري. حيث يبعد عن وسط مدينة دبي بما كلفني 65 درهم إمارتي بالتاكسي. كان إيجاد تاكسي امرا عسيرا حيث يبعد الفندق عن الطريق الرئيسي كونه جديد و صغير فلم يعلم سائقي التاكسي بوجوده. كان علي أن أتصل بخدمة تاكسي الفندق لأسأل عن الاتجاهات. وعندما طلبت جردل ثلج دفعت عليه 10 دراهم. أفضل الطرق للوصول لداون تاون هو تاكسي لراديسون بلو على الخليج، ومن ثم المشي إلى المحطة المتحدة وأخذ المترو بقيمة 6.50 درهم. ومن مميزات وجودك خارج مركز سياحي هو أنك تجد من السوبر ماركت المحلية الرخيصة الأسعار للمشروبات والياه والنقانق. وفي المغادرة كان الفندق على بعد نحو 20 دقيقة من المطار. طلبنا حجز تاكسي لكن إجراءات الفنادق في دبي صعبة لكن ما دبروه هو أشبه بسيارة بسائق خاص. تكلفك حوالي 80 درهم وهو ضعف ما يمكن أن يأخذه أي تاكسي. وبشكل عام أنا سعيد بإقامتي. جودة عالية والسعر عظيم مقارنة بالفنادق ذات الشاطيء والسلاسل الفندقية الكبيرة. إذا كنت ستقيم لعدة ليالي للتنزه البحري لا تمانع السفر من وإلى أماكن الجذب السياحي مع فريق عمل متعاون وودود.\n,1
962,لا توجد ملاحظات تذكر \nالإقامة بالفندق جيدة جداً ومميزاته هي قربه من قاعات السفر، الهدوء، صحن الفواكه الترحيبي، والإنترنت السريع ولكن يجب معرفة أن الغرف الواقعة في كونكورس سي تقع في تيرمينال 1 وهي بعيدة جداً عن تيرمينال 3 ، لذا فإن كانت بوابة مغادرتك في تيرمينال 3 فلا تختار غرف في كونكورس سي لأنك ستحتاج إلى 30 دقيقة مشي داخل المطار للوصول، وكذلك لا يوجد بحمامات الغرف خراطيم مياه للتنظيف مع أن الفندق يقع في بلد مسلم شرقي ، والسعر مبالغ فيه أيضاً، وضبط التكييف معقد نوعاً ما، وعموما الفندق رائع وأنصح به بشدة خاصة للعوائل التي معها أطفال صغار ورضع حيث بإمكانهم إختيار غرفتين موصولتين ببعض وتسجيل الخروج يكون بعد 24 ساعة من تسجيل الدخول وهذه ميزة فنادق المطارات عموماً.\n,1
963,فندق ترانزيت \nأقمتُ هنا بسبب 12 ساعة توقف، كنت احتاجها بشدة بعد 14 ساعة طيران. في البداية كان من الصعب العثور على المكان بعد النزول من الطائرة. وكان يتوجب عليَّ الحصول على الاتجاه إلى المنشأة من العديد من الأشخاص حيث لم تكن هناك أي علامة من\nالبوابة إلى الفند,1

In [ ]:
# Check the column names
print(df.columns)

# Check for duplicate values (adjust the column name if necessary)
duplicates_count = df.duplicated(subset=['text']).sum()
print(f"Number of duplicate values: {duplicates_count}")

# Check for null values
null_values_count = df.isnull().sum().sum()
print(f"Number of null values: {null_values_count}")

Index(['text', 'polarity'], dtype='object')
Number of duplicate values: 0
Number of null values: 0

In [ ]:
import pandas as pd
import re

def clean_arabic_text(text):

    # Remove diacritics
    text = strip_tashkeel(text)
    # Remove punctuation and non-Arabic characters
    cleaned_text = re.sub(r'[^\u0600-\u06FF\s]', '', text)

    # Remove extra spaces
    cleaned_text = re.sub(r'\s+', ' ', cleaned_text).strip()
    if not re.search(r'[\u0600-\u06FF]', text):
        return ''

    return cleaned_text
# Apply the cleaning function to the 'text' column
df['text'] = df['text'].apply(clean_arabic_text)

In [ ]:
df

,text,polarity
0,المكان الذي يمكنك فيه مراجعة الذات والتفكر هو كوكروبيت، غانا ثمة الكثير عند زيارة غانا وعلى الرغم من الفقر الذي سوف تلاحظه على طريقك إلى بيغ ميلي باكيارد، وجدت أن الناس في غانا يملكون ثراء القلب حتى رغم العوز بيغ ميلي باكيارد هو مكان يمكنني فيه مراجعة الذات والتفكر التقيت أشخاصا كانوا يعملون على مبادرات مختلفة بيغ ميلي هو مكان يمكننا فيه تبادل الملاحظات والآراء بيغ ميلي مليء بالسلام وهادئ للغاية الطعام ممتاز جدا الطهاة ممتازون وبالإضافة إلى ذلك لا بد من الإشارة إلى أن العمال الذين لا يكلون، ويحرصون على سعادة نزلائهم هم من يجعلون المكان مضيافا هناك خيبة أمل واحدة كبيرة رغم أن الفنون والأشغال اليدوية يمكن شراؤها في الموقع إلا أن الأسعار غالية مؤخرا أزالت السلطات في كوكروبيت محلات التجار الواقعة خارج شاطئ بيغ ميلي كانت منتجات التجار أرخص لا يزال هناك محل تجاري متجر مايسترو للفن الإفريقي في كوكروبيت يعرض الفنون والأشغال اليدوية الفريدة والملابس واللوحات اشتريت لوحات مذهلة لايمكنك أن تجدها في بيغ ميلي عندما تزور بيغ ميلي من فضلك خذ لحظة للذهاب إلى الشاطئ وعلى يمينك ستجد متجر مايسترو للفن الإفريقي المذهل لا تنخدع بأسعار التجار في بيغ ميلي باكيارد استمتع بالموسيقى والناس الرجاء أن تقضي وقتا ممتعا,1
1,موقع رائع وحديقة رائعة ويستحق نجمة إضافية على الرغم من أن الغرف ليست فاخرة، فهي نظيفة جدا وتعمل بشكل مثالي بالتأكيد هناك بعض التصرفات الفردية والجماعية، ولكن كان هناك تكييف هواء كبير وجيد ونوافذ مزدوجة جيدة مع شاشات منطقة الحديقة تحتوى على مطاعم بالإضافة إلى بار رياضي تبلغ تكلفة الإنترنت اللاسلكي دولار للساعة، ولا يوجد خصم على الفترات الأطول، لذلك اضطررت إلى إغلاق حاسوبي أكثر إف و بي رخيص جدا يبدو أن هناك العديد من الزوار الأجانب هناك دولار أمريكي لليلة بما في ذلك بوفيه إفطار بمستوى نجمة واحدة إقامة أفضل بكثير مما اعتقدت، سنعود بالتأكيد شملت الإقامات السابقة فندق الأفريقية ريجنت و الدخول بالمطار غرب فندق خيارريجينت أفريكان وفندق إيربيورت ويست خيار قوي لتلك المنطقة من المدينة حركة المرور في أكرا مصابة بالشلل، لذا قم بعقد اجتماعاتك في فندق بالوما وهو معروف جيدا,0
2,أسوأ فندق أقمت فيه على الإطلاق يستغرق تسجيل الوصول حوالي دقيقة، باهظ الثمن، غرف قديمة جدا وقذرة، سجادة قذرة جدا فى المجمل تجربة سيئة للغاية مثل هذا الفندق سيكون في آسيا، نجمة واحدة، ويمكن أن أذهب في مايو دولار أمريكي السعر في فندق نوفوتيل حوالي دولار أمريكي,-1
3,بدون روح كأنه فندق ثلاثة نجوم بدون إدارة احترافية، فإن هذا الفندق يبدو كمركب ضائع في البحر الغرف موزعة بطريقة عشوائية والإفطار هو نقانق باردة سخيفة ونفس السلطة القديمة في كل يوم كان مكيف الهواء يثير الضوضاء في الغرفة ومن المستحيل إيقافه ولكن مركز صحي رائع,0
4,فندق جميل مع سوء الإدارة والخدمات من الخارج بدا مبشرا، لكن خيبة الأمل بدأت في وقت الغداء، جودة الطعام سيئة سيئة سيئة، والحساء كان مزريا جدا، والفواكه جودتها سيئة البكيخ كان متعفنا، واو اشتكى زملائي من عدم وجود مناشف في غرفهم في حوالي الساعة مساء، والبعض لم تكن أسرتهم مرتبة حتى الساعة مساء تناولنا عشاء مكسيكيا ومرة أخرى كانت قائمة الطعام مزرية لن أقيم هنا أبدا، على الأقل أتحدث عن نفسي,-1
...,...,...
959,ما تتوقعه من فندق إذا اقمت في فندق الصغير في المملكة المتحدة، فأنت تعلم ما تتوقعه في هذا الفندق، فهو تقريبا متسق مع نفس المستوى القياسي كانت الغرف نظيفة وبها ديكورات جميلة وواسعة لا توجد مرافق كثيرة لكن يوجد حمام سباحة صغير بالطابق الأخير وبارمطعم ومحل مفتوح ساعة الفندق قري من المطار لكن مسافة لا يمكن قطعها سيرا سيلزم ركوب أتوبيس يغادر كل دقيقة أقرب محطة مترو الإمارات على مسافة دقيقة سيرا يدير الفندق أتوبيسات إلى العديد من الأماكن اتسم طاقم العمل بالترحاب والانتباه وكان الفندق منعزلا بشكل جيد عن ضوضاء المطار,1
960,فندق نجوم تنافسي جدا كان فندق الأجازات الصغير محبطا إلى حد ما أقمت في هذا الفندق لمدة ليلة واحدة أثناء رحلتي إلى تايلاند في يناير وعودتي في فبراير اتسم طاقم العمل بالود الشديد وبدا الأمر كما يتم الترويج له في الإعلانات كان يوجد عدد كاف من طاقم العمل عند تسجيل الدخول كان يوجد أو مقابل في الفندق المجاور كانت الغرفة مريحة وفوق المتوسط بالنسبة لهذه الفئة تتضمن سخان مياه للقهوة والشاي كان النوم رائعا من ناحية السرير وانعدام الضوضاء كما كان سائق الأتوبيس ودودا ويبدو سعيدا بمساعدة الغير، وكانت ماعيد منضبطة بالساعة ونصف الساعة الشيء السلبي هو الفطائرة التي يتم تقديمها في الفطور لكن يبدوأنه يوجد محل قهوة عند المدخل مفتوح ساعة نقطة أخيرة الأسعار تنافسية مع الفنادق الأخرى القريبة من المطار دقائق بالأتوبيس رغم أن الفطورلم يكن متضمنا بعض الفنادق تقدم فطورا مجانيا الاختيار لك,1
961,يمكن أن أقيم فيه مجددا الفندق جديد و قد تم تشطيبه وفقا لمواصفات غاية في الجودة طاقم العمل معظمهم من الشرق و هم غاية في اللطف و التعاون الغرف مزودة بتقنية تكنولوجية عالية ذات نظام تحكم رقمي للإضاءة و الستائر إلخإضافة إلي مستلزمات فائقة الجودة لدورات المياهكان السعر متميز جدا و لكنه اختلف كثيرا بناء علي من قام بالحجزاستخدم بعد المواقع الخاصة بالمقارنة لمعرفة أفضل الأسعاريقع بالقرب من ميناء كروز و يتكلف التاكسي درهم اماراتي دولار امريكيأما عن العيوبالنوم ليس مزعج علي متن الطائرة إلا أن سقف البار ليس موجود تقريبا لذلك قد تعلو الضوضاء في بعض الأحيانو كذلك خدمة الواي فاي المجانية ليست فقط متقلبقة و لكن تتطلب تغيير كلمة السر بشكل يومي إضافة إلي كونها بطيئة جدا و لا تقبل تجديد الإيميل لذلك كان علي فعل ذلك بمركز دبي التجاري حيث يبعد عن وسط مدينة دبي بما كلفني درهم إمارتي بالتاكسي كان إيجاد تاكسي امرا عسيرا حيث يبعد الفندق عن الطريق الرئيسي كونه جديد و صغير فلم يعلم سائقي التاكسي بوجوده كان علي أن أتصل بخدمة تاكسي الفندق لأسأل عن الاتجاهات وعندما طلبت جردل ثلج دفعت عليه دراهم أفضل الطرق للوصول لداون تاون هو تاكسي لراديسون بلو على الخليج، ومن ثم المشي إلى المحطة المتحدة وأخذ المترو بقيمة درهم ومن مميزات وجودك خارج مركز سياحي هو أنك تجد من السوبر ماركت المحلية الرخيصة الأسعار للمشروبات والياه والنقانق وفي المغادرة كان الفندق على بعد نحو دقيقة من المطار طلبنا حجز تاكسي لكن إجراءات الفنادق في دبي صعبة لكن ما دبروه هو أشبه بسيارة بسائق خاص تكلفك حوالي درهم وهو ضعف ما يمكن أن يأخذه أي تاكسي وبشكل عام أنا سعيد بإقامتي جودة عالية والسعر عظيم مقارنة بالفنادق ذات الشاطيء والسلاسل الفندقية الكبيرة إذا كنت ستقيم لعدة ليالي للتنزه البحري لا تمانع السفر من وإلى أماكن الجذب السياحي مع فريق عمل متعاون وودود,1
962,لا توجد ملاحظات تذكر الإقامة بالفندق جيدة جدا ومميزاته هي قربه من قاعات السفر، الهدوء، صحن الفواكه الترحيبي، والإنترنت السريع ولكن يجب معرفة أن الغرف الواقعة في كونكورس سي تقع في تيرمينال وهي بعيدة جدا عن تيرمينال ، لذا فإن كانت بوابة مغادرتك في تيرمينال فلا تختار غرف في كونكورس سي لأنك ستحتاج إلى دقيقة مشي داخل المطار للوصول، وكذلك لا يوجد بحمامات الغرف خراطيم مياه للتنظيف مع أن الفندق يقع في بلد مسلم شرقي ، والسعر مبالغ فيه أيضا، وضبط التكييف معقد نوعا ما، وعموما الفندق رائع وأنصح به بشدة خاصة للعوائل التي معها أطفال صغار ورضع حيث بإمكانهم إختيار غرفتين موصولتين ببعض وتسجيل الخروج يكون بعد ساعة من تسجيل الدخول وهذه ميزة فنادق المطارات عموما,1
963,فندق ترانزيت أقمت هنا بسبب ساعة توقف، كنت احتاجها بشدة بعد ساعة طيران في البداية كان من الصعب العثور على المكان بعد النزول من الطائرة وكان يتوجب علي الحصول على الاتجاه إلى المنشأة من العديد من الأشخاص حيث لم تكن هناك أي علامة من البوابة إلى الفند,1

In [ ]:
# Separate the DataFrame based on the polarity
df_normal = df[df['polarity'] == 0]
df_positive = df[df['polarity'] == 1]
df_negative = df[df['polarity'] == -1]

# Display the first few rows of each DataFrame to verify
print("Normal reviews:")
print(df_normal.head())

print("Positive reviews:")
print(df_positive.head())

print("Negative reviews:")
print(df_negative.head())

Normal reviews:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 text  \
1                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   موقع رائع وحديقة رائعة ويستحق نجمة إضافية على الرغم من أن الغرف ليست فاخرة، فهي نظيفة جدا وتعمل بشكل مثالي بالتأكيد هناك بعض التصرفات الفردية والجماعية، ولكن كان هناك تكييف هواء كبير وجيد ونوافذ مزدوجة جيدة مع شاشات منطقة الحديقة تحتوى على مطاعم بالإضافة إلى بار رياضي تبلغ تكلفة الإنترنت اللاسلكي دولار للساعة، ولا يوجد خصم على الفترات الأطول، لذلك اضطررت إلى إغلاق حاسوبي أكثر إف و بي رخيص جدا يبدو أن هناك العديد من الزوار الأجانب هناك دولار أمريكي لليلة بما في ذلك بوفيه إفطار بمستوى نجمة واحدة إقامة أفضل بكثير مما اعتقدت، سنعود بالتأكيد شملت الإقامات السابقة فندق الأفريقية ريجنت و الدخول بالمطار غرب فندق خيارريجينت أفريكان وفندق إيربيورت ويست خيار قوي لتلك المنطقة من المدينة حركة المرور في أكرا مصابة بالشلل، لذا قم بعقد اجتماعاتك في فندق بالوما وهو معروف جيدا
3                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     بدون روح كأنه فندق ثلاثة نجوم بدون إدارة احترافية، فإن هذا الفندق يبدو كمركب ضائع في البحر الغرف موزعة بطريقة عشوائية والإفطار هو نقانق باردة سخيفة ونفس السلطة القديمة في كل يوم كان مكيف الهواء يثير الضوضاء في الغرفة ومن المستحيل إيقافه ولكن مركز صحي رائع
12                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   ينصح به للغاية للسائحين من أصحاب الميزانيات المنخفضة الموقع رائع حيث يقع على بعد مسافة قصيرة من المعالم السياحية الرئيسية ومحطات وسائل النقل العام الغرفة حصلنا على غرفة مزدوجة بسعر منخفض توأم مع حمام نظيف وتلفزيون وشرفة صغيرة حوالي متر متر الخدمة خدمة غرف يومية، مكتب الاستقبال يعمل على مدار ساعة طوال الأسبوع الجانب الإيجابي قيمة جيدة مقابل المال الجانب السلبي صاخب نوعا ما في المساء
18                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          الفندق لطيف ولكن الطعام كان فظيعا كان فندقا جميلا ونظيفا لا تتناول الطعام في الفندق، إنه مضيعة للمال، وهذا أسوأ مكان تناولت فيه طعاما، فقد توقفنا عن تناول الطعام في الفندق وكنا نأكل في المدينة بنصف السعر وليس في الفندق لكننا جعلنا الفندق يرد لنا الأموال التي دفعناها للطعام مقدما إذا أوصاك أحد المرشدين السياحيين بالذهاب إلى أحد المطاعم فلا تتبعه، لأنهم يأخذون منك ضعف السعر لأنهم يأكلون هناك مجانا والمطعم يحضر السياح ليستغلهم أحضرنا أحد المرشدين السياحيين إلى مطعم، وطلبنا طعاما وعندما جاؤوا بالفاتورة وجدنا أنهم قد احتسبوا لفافتين بـ يورو وزبدة، ونحن لم نطلبها لكنهم قدموها مع الوجبة تحقق دائما من أسعار المشروبات وإلا فسوف يحتسبون عليك ضعف السعر
19  عطلة جيدة، ولكنه فندق نجوم وليس نجوم عدنا للتو من كلوب هامبريا مع طفلينا بأعمار و سنة، وكان هناك أصدقاء معنا مع أولادهم بأعمار و سنة لقد استمتعنا بمنتجع عطلتنا الجميل بعض المقاهي الصغيرة والبارات على بعد مسافة قصيرة سيرا على الأقدام، وتوجد عدة متاجر على الشاطئ الذي يتميز بالجمال الطعام لم يكن رائعا، والخيارات محدودة جدا طبقان رئيسيان كل ليلة وكانا على مستوى شنيع، ورقائق البطاطس والمكرونة والسلطات والحلويات كانت رديئة لقد قمنا بعطلات شاملة كل شيء في السنوات القليلة الماضية، وهذه العطلة لم تكن جيدة فعلا المشروبات في المطعم بنظام الخدمة الذاتية، ولكن بار الوجبات الخفيفة أثناء النهار تكون عليه طوابير، طوابير، طوابير هناك شخص واحد يعمل وهو يحاول تقديم المشروبات والطعام ومرة أخرى في المساء عندما تذهب إلى الترفيه الليلي، تكون هناك طوابير للمشروبات، ولا توجد مقاعد كافية بالنسبة لعدد الغرف في المجمع في الحقيقة ذهبنا إلى سوبر ماركت لجلب النبيذ والبيرة، وبقينا في الغرفة بضع ليال نادي الأطفال مروع لم يقدموا ما قالوا عليه في النشرات الأسبوعية يبدو إنهم قاموا فقط بتقديم أوراق للتلوين إلى جميع الأطفال يمكن أن يكون مستوى التنظيف أفضل من ذلك الحمام لم يتم تنظيفه بشكل صحيح ولا المطبخ والأسرة غير مريحة على الإطلاق شيء واحد يجب أن أثني على هذا الفندق بخصوصه هو أحد أعضاء فريق العمل برونو، كان رائعا للغاية ومتعاون جدا ترك ابني حقيبة تحتوي على جهاز البلاي ستيشن المحمول، والآي بود، والمال وكل شيء اعتقدنا أننا لن نراها مرة أخرى ولكن برونو اتصل بهم مباشرة، وقالوا إنه تم العثور عليها ولكن مرت أيام ولم تتم إعادتها إلينا بعد، فقام برونو بالفعل بإرسال شخص من الفندق إلى المطار لاستلامها كنا سعداء للغاية لقد أحببت البرتغال والمنتجع ولكننا لن نقيم هنا مرة أخرى

    polarity
1          0
3          0
12         0
18         0
19         0
Positive reviews:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 text  \
0  المكان الذي يمكنك فيه مراجعة الذات والتفكر هو كوكروبيت، غانا ثمة الكثير عند زيارة غانا وعلى الرغم من الفقر الذي سوف تلاحظه على طريقك إلى بيغ ميلي باكيارد، وجدت أن الناس في غانا يملكون ثراء القلب حتى رغم العوز بيغ ميلي باكيارد هو مكان يمكنني فيه مراجعة الذات والتفكر التقيت أشخاصا كانوا يعملون على مبادرات مختلفة بيغ ميلي هو مكان يمكننا فيه تبادل الملاحظات والآراء بيغ ميلي مليء بالسلام وهادئ للغاية الطعام ممتاز جدا الطهاة ممتازون وبالإضافة إلى ذلك لا بد من الإشارة إلى أن العمال الذين لا يكلون، ويحرصون على سعادة نزلائهم هم من يجعلون المكان مضيافا هناك خيبة أمل واحدة كبيرة رغم أن الفنون والأشغال اليدوية يمكن شراؤها في الموقع إلا أن الأسعار غالية مؤخرا أزالت السلطات في كوكروبيت محلات التجار الواقعة خارج شاطئ بيغ ميلي كانت منتجات التجار أرخص لا يزال هناك محل تجاري متجر مايسترو للفن الإفريقي في كوكروبيت يعرض الفنون والأشغال اليدوية الفريدة والملابس واللوحات اشتريت لوحات مذهلة لايمكنك أن تجدها في بيغ ميلي عندما تزور بيغ ميلي من فضلك خذ لحظة للذهاب إلى الشاطئ وعلى يمينك ستجد متجر مايسترو للفن الإفريقي المذهل لا تنخدع بأسعار التجار في بيغ ميلي باكيارد استمتع بالموسيقى والناس الرجاء أن تقضي وقتا ممتعا
5                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          فندق جميل، منظر رائع من بركة السباحة على السطح فندق جميل، ديكور مريح جدا، طاقم عمل ودود، أسرة مريحة، موقع رائع وبركة سباحة جميلة وشرفة على السطح للاستمتاع بالمناظر الإفطار رائع أيضا مع الكثير من الكعك أحب أن أعود قريبا
6                                                                                                                                                              مكان لطيف وهادئ بعيدا عن الزحام عثرت على هذا المكان عن طريق موقع تريب أدفايزور ومرة أخرى كان جيدا وفندق في آي بي إكسيكوتيف هو واحد من فنادق كبار الشخصيات العديدة في هذه المنطقة وتمت ترقية غرفتي عند وصولي الغرفة واسعة جدا مع ثلاجة صغيرة ونافذة تفتح على هواء منعش ويوجد مكيف هواء وهو يقع خارج ساحة ماركيز بومبال وهو ما يجعله على بعد مسافة قصيرة بالمترو من جميع الأنشطة القائمون على العناية بالغرف قاموا بعمل عظيم كان فريق العمل ودودا ومتعاونا استنادا إلى التعليقات الموجودة على موقع تريب أدفايزر، لم أتناول الإفطار هناك يورو ومشيت إلى المقهى الموجود بالقرب من محطة المترو حيث حصلت على معجنات رائعة وقهوة حليب طازجة مقابل يورو يوجد مجفف شعر بالغرفة لا توجد ساعة يوجد العديد من ملصقات كاندينسكي المستخدمة في الأعمال الفنية الستائر جيدة وقد كانت تحجب الضوء بقماش شفاف أبيض حي جيد به عاملون وبعض الفنادق توجد العديد من محلات الأزياء بالجوار وكذلك بين الحديقة ومحطة مترو أفينيدا خدمة الإنترنت الدفع فيها حسب الاستخدام وتكلفة ساعة من استخدام الإنترنت هي يورو
7                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   راقي و كلاسيكي فندق كبير مصمم بفن الديكور الجميل آرت ديكو يقع في منطقة هادئة خارج أفينديا ليبرداد كل شيء عن المكان يشير إلى درجة من الرقي و الأصالة الغيرملفتة للنظر غرف ممتازة، أسرة ضخمة و مريحة و دورات مياة وآثاث مصممين بفن آرت ديكو وجبات إفطار لذيذة، و بعد الظهر يقدم شاي مجاني في المكتبة و خمرة في المساء مكان جميل حقا
8                                                                                                                                                      تحذير للرجال الذي يحبون تناول بعض البيرة ليلا شيء وحيد أود قوله هو أنه لا توجد أية مشكلة في فندق كلاريون سويتس في لشبونة أو في أي مكان آخر في هذا الشأن، مشكلتي كانت الموقع بعد يوم حافل في رحلة سياحية، أود تناول العشاء ثم الخروج لتناول بعض البيرة كانت الساعة مساء في هذه المنطقة عندما لاحظت أن الأماكن الوحيدة التي تقدم البيرة هي محلات الكيك حيث تكون البيرة متاحة، لكنك تجلس على طاولة صغيرة على كراسي مطبخ معدنية أنبوبية رديئة لا يوجد بار على الإطلاق كانت كل المحلات تستعد للإغلاق في هذه المنطقة بأكملها، وفي كل المناطق القريبة التي يمكن الوصول إليها سيرا على الأقدام، لم أجد بارا وحدا انتهيت من تناول البيرة في ماكدونالدز بينما ابنتي وأمي يتناولان البرجر في وقت لاحق دخلت إلى فندق ريتز فور سيزونز وتناولت كوبين إضافيين من البيرة في بار الفندق تكلف الكوب يورو، إلا إنها كانت مرة بعض الشيء يكفي القول إنك إذا كنت مثلي تحب الخروج من الفندق لتناول البيرة في بار محلي، فابحث عن مكان آخر أما إذا كنت تحب القهوة والكعك والنوم في الساعة مساء، فهذا الفندق سيكون رائعا

   polarity
0         1
5         1
6         1
7         1
8         1
Negative reviews:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 text  \
2                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   أسوأ فندق أقمت فيه على الإطلاق يستغرق تسجيل الوصول حوالي دقيقة، باهظ الثمن، غرف قديمة جدا وقذرة، سجادة قذرة جدا فى المجمل تجربة سيئة للغاية مثل هذا الفندق سيكون في آسيا، نجمة واحدة، ويمكن أن أذهب في مايو دولار أمريكي السعر في فندق نوفوتيل حوالي دولار أمريكي
4                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  فندق جميل مع سوء الإدارة والخدمات من الخارج بدا مبشرا، لكن خيبة الأمل بدأت في وقت الغداء، جودة الطعام سيئة سيئة سيئة، والحساء كان مزريا جدا، والفواكه جودتها سيئة البكيخ كان متعفنا، واو اشتكى زملائي من عدم وجود مناشف في غرفهم في حوالي الساعة مساء، والبعض لم تكن أسرتهم مرتبة حتى الساعة مساء تناولنا عشاء مكسيكيا ومرة أخرى كانت قائمة الطعام مزرية لن أقيم هنا أبدا، على الأقل أتحدث عن نفسي

In [ ]:
# Count the number of samples in each class
class_counts = df['polarity'].value_counts()
print("Class distribution:")
print(class_counts)

Class distribution:
polarity
 1    738
-1    114
 0    112
Name: count, dtype: int64

In [ ]:
from imblearn.over_sampling import RandomOverSampler
import pandas as pd

# Separate features and target
X = df['text']
y = df['polarity']

# Create the oversampler
ros = RandomOverSampler(sampling_strategy='auto', random_state=42)

# Fit and resample
X_resampled, y_resampled = ros.fit_resample(X.values.reshape(-1, 1), y)

# Create a new DataFrame with the resampled data
df_balanced = pd.DataFrame({
    'text': X_resampled.flatten(),
    'polarity': y_resampled
})

# Check the new distribution
balanced_class_counts = df_balanced['polarity'].value_counts()
print("Balanced class distribution:")
print(balanced_class_counts)

Balanced class distribution:
polarity
 1    738
 0    738
-1    738
Name: count, dtype: int64

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

# Initialize the TF-IDF Vectorizer
tfidf_vectorizer = TfidfVectorizer()

# Fit and transform the text data
X_tfidf = tfidf_vectorizer.fit_transform(df_balanced['text'])

In [ ]:
from sklearn.model_selection import train_test_split

# Split the data
X_train, X_test, y_train, y_test = train_test_split(X_tfidf, df_balanced['polarity'], test_size=0.2, random_state=42)

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report

# Initialize the Logistic Regression model
model = LogisticRegression(max_iter=1000)

# Train the model
model.fit(X_train, y_train)

# Predict on the test set
y_pred = model.predict(X_test)

# Evaluate the model
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

          -1       0.99      1.00      0.99       144
           0       0.97      1.00      0.99       148
           1       1.00      0.96      0.98       151

    accuracy                           0.99       443
   macro avg       0.99      0.99      0.99       443
weighted avg       0.99      0.99      0.99       443

In [ ]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.model_selection import cross_val_score
import matplotlib.pyplot as plt

# Evaluate model performance on training and test sets
y_train_pred = model.predict(X_train)
y_test_pred = model.predict(X_test)

# Calculate accuracy
train_accuracy = accuracy_score(y_train, y_train_pred)
test_accuracy = accuracy_score(y_test, y_test_pred)

print(f"Training Accuracy: {train_accuracy}")
print(f"Test Accuracy: {test_accuracy}")

# Print classification report
print("Classification Report (Test Data):")
print(classification_report(y_test, y_test_pred))

Training Accuracy: 0.9994353472614342
Test Accuracy: 0.9864559819413092
Classification Report (Test Data):
              precision    recall  f1-score   support

          -1       0.99      1.00      0.99       144
           0       0.97      1.00      0.99       148
           1       1.00      0.96      0.98       151

    accuracy                           0.99       443
   macro avg       0.99      0.99      0.99       443
weighted avg       0.99      0.99      0.99       443